KIT-136 done
WildCodeSchool/bugs-squad-project-KIT pull request #17
Opened 2023-06-20 14:36 UTC by emmirose

2023-06-20 14:38 UTC, emmirose commented
![Capture d'écran 2023-06-20 163726](https://github.com/WildCodeSchool/bugs-squad-project-KIT/assets/114017087/6bacb438-7606-4017-9067-420fede8e8f3)

2023-06-20 14:38 UTC, emmirose commented
Le form est dans la même grid que les collections

2023-06-21 08:04 UTC, Tylyfox requested changes

2023-06-21 09:36 UTC, emmirose commented on src/app/pages/collections/collections.component.scss
done

2023-06-21 09:36 UTC, emmirose commented on src/app/pages/collections/collections.component.scss
> +
done

2023-06-21 09:36 UTC, emmirose commented on src/app/pages/collections/collections.component.ts
> +import { faPencil } from '@fortawesome/free-solid-svg-icons';
done

2023-06-21 09:38 UTC, Tylyfox submitted a review, later dismissed

2023-06-21 10:39 UTC, Benja-san submitted a review, later dismissed
Remove unnecessaries comments before merging

2023-06-21 10:39 UTC, Benja-san commented on src/app/pages/collections/collections.component.html
>    <!-- display all of my Collection components in the collections array, with the associated style -->
remove dead code ?

2023-06-21 11:45 UTC, Tylyfox approved these changes

2023-06-21 12:09 UTC, Benja-san submitted a review, later dismissed

2023-06-21 12:35 UTC, Tylyfox approved these changes

2023-06-21 12:41 UTC, Benja-san approved these changes

2023-06-21 12:41 UTC, Benja-san commented on src/app/pages/collections/collections.component.html
> +    <!-- Display the Collection Component instance with the React collection -->
remove dead code please

2023-06-21 12:42 UTC, merged