Kit 165 front
WildCodeSchool/bugs-squad-project-KIT pull request #35
Opened 2023-07-05 14:04 UTC by emmirose

HTTP request to get all todos

2023-07-05 14:11 UTC, emericb requested changes

2023-07-05 14:11 UTC, emericb commented on src/app/components/todolist/todolist.component.html
remove dead code

2023-07-05 14:15 UTC, emericb approved these changes

2023-07-06 07:39 UTC, Benja-san requested changes

2023-07-06 07:39 UTC, Benja-san commented on src/app/pages/todolists/todolists.component.ts
> +      console.log(this.todolists);
remove console logs

2023-07-06 07:39 UTC, Benja-san commented on src/app/pages/todolists/todolists.component.ts
> +  todolist!: ToDoList;
what does this property stand for ?

2023-07-06 07:51 UTC, emmirose commented on src/app/pages/todolists/todolists.component.ts
> +  todolist!: ToDoList;
Not necessary anymore !

2023-07-06 07:52 UTC, emericb submitted a review, later dismissed

2023-07-06 08:03 UTC, Benja-san submitted a review, later dismissed

2023-07-06 09:22 UTC, emericb approved these changes

2023-07-06 09:23 UTC, Benja-san approved these changes

2023-07-06 09:23 UTC, merged