Kit 172
WildCodeSchool/bugs-squad-project-KIT pull request #50
Opened 2023-07-17 12:27 UTC by emmirose

Composant todos fav à afficher sur le dashboard
responsive
+ alertes à la suppression

2023-07-17 12:34 UTC, Newaluigi submitted a review, later dismissed

2023-07-17 14:13 UTC, Newaluigi approved these changes

2023-07-18 12:39 UTC, Benja-san requested changes

2023-07-18 12:39 UTC, Benja-san commented on src/app/components/todolist/todolist.component.scss
> +// TODOLIST
dead code

2023-07-18 12:39 UTC, Benja-san commented on src/app/components/todolist/todolist.component.scss
> +// MODALS
dead code

2023-07-18 12:42 UTC, Benja-san approved these changes

2023-07-18 12:42 UTC, merged