KIT-274
WildCodeSchool/bugs-squad-project-KIT pull request #53
Opened 2023-07-18 12:46 UTC by emericb

2023-07-18 13:09 UTC, emmirose commented on src/app/models/Link.ts
> +  constructor(public id: number, public url: string, public title: string | null, public collectionId: number) {}
Tu as besoin du collectionId ?

2023-07-18 13:13 UTC, emmirose approved these changes

2023-07-18 14:37 UTC, Benja-san requested changes

2023-07-18 14:37 UTC, Benja-san commented on src/app/components/collection-form-update/collection-form-update.component.html
> +  <!-- Formulaire update de collection -->
remove dead code

2023-07-18 14:37 UTC, Benja-san commented on src/app/components/collection-form/collection-form.component.html
> +  <!-- Formulaire de création de collection -->
remove dead code

2023-07-18 14:56 UTC, Benja-san approved these changes

2023-07-19 13:13 UTC, emmirose approved these changes

2023-07-19 13:13 UTC, merged