Kit 333 2
WildCodeSchool/bugs-squad-project-KIT pull request #54
Opened 2023-07-18 14:55 UTC by Newaluigi

# Result

![Capture d’écran 2023-07-18 165439](https://github.com/WildCodeSchool/bugs-squad-project-KIT/assets/108535805/ae6ffe1b-f3c5-47cd-a43b-5b8dc4c2437b)

# On progress

* Allow to add one widget of each and disable in gray in the sidebar the one added
* Fix initial position

2023-07-19 13:20 UTC, emmirose requested changes

2023-07-19 13:36 UTC, emmirose approved these changes

2023-07-19 14:22 UTC, Benja-san requested changes

2023-07-19 14:22 UTC, Benja-san commented on src/app/components/dashboard/dashboard.component.ts
> +        console.log(e.type + ' ' + items.length + ' items:' + str);
remove console log

2023-07-19 14:22 UTC, Benja-san commented on src/app/components/dashboard/dashboard.component.ts
> +    // this.gridStackService.saveWidgetsPositions(widgetPositions).subscribe(
remove dead code

2023-07-20 06:59 UTC, Benja-san approved these changes

2023-07-20 07:15 UTC, merged