KIT-233 - Add Favorite RssFeed
WildCodeSchool/bugs-squad-project-KIT pull request #58
Opened 2023-07-19 14:39 UTC by Tylyfox

2023-07-19 14:47 UTC, emmirose requested changes

2023-07-19 14:47 UTC, emmirose commented on src/app/components/rss/sidebar-rss-feed/sidebar-rss-feed.component.ts
> +        console.log('Réponse de la requête PUT :', response);
console.log

2023-07-19 14:47 UTC, emmirose commented on src/app/services/rssService/rss.service.ts
> +    console.log(updateData);
console.log

2023-07-19 14:50 UTC, emmirose submitted a review, later dismissed

2023-07-20 07:51 UTC, emmirose approved these changes

2023-07-20 08:14 UTC, Benja-san approved these changes

2023-07-20 08:16 UTC, merged